mongo:
    image: mymongo
    restart: always
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    app:
      - build: .
      - dockerfile: Dockerfile
      - ports:
          - "8085:8080"
          -
#version: '3'
#services:
#    mongodb:
#      image: mongo
#      ports:
#        - "27017:27017"
#      app:
#        - build: .
#        - dockerfile: Dockerfile
#        - ports:
#            - "8085:8080"
#      environment:
#        - MONGO_INITDB_ROOT_USERNAME=admin
#        - MONGO_INITDB_ROOT_PASSWORD=password
#      volumes:
#        - mongo-data:/data/db
#        -
#      mongo-express:
#        image: mongo-express
#        ports:
#          - "8080:8081"
#        environment:
#          - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#          - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#          - ME_CONFIG_MONGODB_SERVER=mongodb
#volumes:
#  mongo-data:
#    driver: local
#